package ValidationLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptInspection = createDescriptorForInspection();
  /*package*/ final ConceptDescriptor myConceptInspections = createDescriptorForInspections();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptInspection, myConceptInspections);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Inspection:
        return myConceptInspection;
      case LanguageConceptSwitch.Inspections:
        return myConceptInspections;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForInspection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ValidationLang", "Inspection", 0xe6eb90594b444f40L, 0xa7a004b2d2ca42dbL, 0x67007b4897dcb4f8L);
    b.class_(false, false, false);
    b.origin("r:b697b1a0-518d-4e1a-812a-6a4574fe7c0f(ValidationLang.structure)/7422067737622263032");
    b.prop("name", 0x67007b4897dcb4f9L, "7422067737622263033");
    b.prop("expression", 0x67007b4897dcb4fbL, "7422067737622263035");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInspections() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ValidationLang", "Inspections", 0xe6eb90594b444f40L, 0xa7a004b2d2ca42dbL, 0x67007b4897dcb4f5L);
    b.class_(false, false, true);
    b.origin("r:b697b1a0-518d-4e1a-812a-6a4574fe7c0f(ValidationLang.structure)/7422067737622263029");
    b.aggregate("inspections", 0x67007b4897dd9737L).target(0xe6eb90594b444f40L, 0xa7a004b2d2ca42dbL, 0x67007b4897dcb4f8L).optional(false).ordered(true).multiple(true).origin("7422067737622320951").done();
    b.alias("inspections");
    return b.create();
  }
}
