package ValidationLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Inspection_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("when (");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xe6eb90594b444f40L, 0xa7a004b2d2ca42dbL, 0x67007b4897dcb4f8L, 0x67007b4897dcb4fbL, "expression")));
    tgs.append(") {");
    tgs.newLine();
    tgs.indent();
    tgs.append("reject reason: ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xe6eb90594b444f40L, 0xa7a004b2d2ca42dbL, 0x67007b4897dcb4f8L, 0x67007b4897dcb4f9L, "name")));
    tgs.append("}");
  }
}
